/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/character_manequin.glb 
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Manequin() {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/character_manequin.glb')
  const { actions, names } = useAnimations(animations, group)

  useEffect (() => {
    actions[names[0]]?.reset().fadeIn(0.5).play()
  })

  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig1Hips} />
          <skinnedMesh castShadow name="Ch36" geometry={nodes.Ch36.geometry} material={materials.Ch36_Body} skeleton={nodes.Ch36.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/character_manequin.glb')
