/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/warrior.glb 
*/

import { useGLTF } from '@react-three/drei'

export function Warrior() {
  const { nodes, materials } = useGLTF('./models/warrior.glb')
  return (
    <group dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh geometry={nodes.BattleAxe_GEO.geometry} material={materials.blinn7} skeleton={nodes.BattleAxe_GEO.skeleton} />
        <skinnedMesh geometry={nodes.MaleBruteA_Bottoms.geometry} material={materials.MaleBruteA_Bottom5} skeleton={nodes.MaleBruteA_Bottoms.skeleton} />
        <skinnedMesh geometry={nodes.MaleBruteA_Earrings.geometry} material={materials.phong4} skeleton={nodes.MaleBruteA_Earrings.skeleton} />
        <skinnedMesh geometry={nodes.MaleBruteA_Eyelashes.geometry} material={materials.Lashes_MAT4} skeleton={nodes.MaleBruteA_Eyelashes.skeleton} />
        <skinnedMesh geometry={nodes.MaleBruteA_Eyes.geometry} material={materials.EyeSpec_MAT4} skeleton={nodes.MaleBruteA_Eyes.skeleton} />
        <skinnedMesh geometry={nodes.MaleBruteA_Hair.geometry} material={materials.MaleBruteA_Hair6} skeleton={nodes.MaleBruteA_Hair.skeleton} />
        <skinnedMesh geometry={nodes.MaleBruteA_Moustaches.geometry} material={materials.MaleBruteA_Moustache5} skeleton={nodes.MaleBruteA_Moustaches.skeleton} />
        <skinnedMesh geometry={nodes.MaleBruteA_Shoes.geometry} material={materials.MaleBruteA_Shoes6} skeleton={nodes.MaleBruteA_Shoes.skeleton} />
        <skinnedMesh geometry={nodes.Mesh007.geometry} material={materials.Body_MAT4} skeleton={nodes.Mesh007.skeleton} />
        <skinnedMesh geometry={nodes.Mesh007_1.geometry} material={materials.EyeSpec_MAT2} skeleton={nodes.Mesh007_1.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/warrior.glb')
